import { CAMData } from '@/types/cam';

export const mockCAMData: CAMData = {
  applicationId: 'LN-2024-001',
  customerName: 'Technocraft Industries Pvt. Ltd.',
  riskScoring: {
    components: [
      {
        category: 'Business Risk',
        weight: 20,
        score: 17,
        maxScore: 20,
        remarks: 'Established business with 12 years track record, diversified customer base',
      },
      {
        category: 'Financial Risk',
        weight: 25,
        score: 20,
        maxScore: 25,
        remarks: 'Healthy profit margins, adequate cash flows, manageable debt levels',
      },
      {
        category: 'Management Risk',
        weight: 15,
        score: 13,
        maxScore: 15,
        remarks: 'Experienced promoter, good succession plan, transparent operations',
      },
      {
        category: 'Industry Risk',
        weight: 15,
        score: 10,
        maxScore: 15,
        remarks: 'Auto sector cyclicality is a concern, but diversification helps',
      },
      {
        category: 'Collateral Risk',
        weight: 15,
        score: 14,
        maxScore: 15,
        remarks: 'Adequate security with owned factory, comfortable LTV ratio',
      },
      {
        category: 'Conduct Risk',
        weight: 10,
        score: 9,
        maxScore: 10,
        remarks: 'Clean credit history, good banking relationship, no adverse remarks',
      },
    ],
    totalScore: 83,
    maxTotalScore: 100,
    riskGrade: 'B',
    riskCategory: 'Moderate Risk',
  },
  proposedTerms: {
    loanAmount: 70000000,
    sanctionedAmount: 63000000,
    tenure: 60,
    interestRate: 11.5,
    processingFee: 0.5,
    emiAmount: 1386250,
    repaymentMode: 'Monthly',
    moratoriumPeriod: 3,
    securityType: 'Factory Premises + Hypothecation of Machinery',
    securityValue: 120000000,
    ltvRatio: 52.5,
    insuranceRequired: true,
    covenants: [
      'Minimum DSCR of 1.5x to be maintained',
      'No dividend distribution without prior approval',
      'Quarterly submission of stock and receivables statement',
      'Annual audited financials within 180 days of FY end',
      'Prior intimation for change in management/shareholding',
      'Insurance policy to be assigned in favor of bank',
    ],
  },
  financialHighlights: [
    {
      metric: 'Debt Service Coverage Ratio (DSCR)',
      value: '2.1x',
      benchmark: 'Min 1.5x',
      status: 'good',
    },
    {
      metric: 'Interest Coverage Ratio (ICR)',
      value: '3.8x',
      benchmark: 'Min 2.0x',
      status: 'good',
    },
    {
      metric: 'Current Ratio',
      value: '1.35',
      benchmark: 'Min 1.25',
      status: 'good',
    },
    {
      metric: 'Debt/Equity Ratio',
      value: '1.2',
      benchmark: 'Max 2.0',
      status: 'good',
    },
    {
      metric: 'Net Profit Margin',
      value: '8.5%',
      benchmark: 'Min 5%',
      status: 'good',
    },
    {
      metric: 'Asset Turnover Ratio',
      value: '1.8x',
      benchmark: 'Min 1.5x',
      status: 'good',
    },
    {
      metric: 'Working Capital Cycle',
      value: '95 days',
      benchmark: 'Max 90 days',
      status: 'average',
    },
    {
      metric: 'Receivables Concentration',
      value: '45%',
      benchmark: 'Max 30%',
      status: 'concern',
    },
  ],
  approvalWorkflow: {
    currentStage: 2,
    totalStages: 4,
    steps: [
      {
        id: 'STEP001',
        role: 'Credit Analyst',
        name: 'Priya Verma',
        status: 'approved',
        comments: 'Recommended for approval with standard conditions. Strong business fundamentals.',
        timestamp: '2024-01-16T14:30:00',
      },
      {
        id: 'STEP002',
        role: 'Branch Credit Manager',
        name: 'Amit Singh',
        status: 'approved',
        comments: 'Concur with analyst recommendation. LTV and DSCR are comfortable.',
        timestamp: '2024-01-17T11:15:00',
      },
      {
        id: 'STEP003',
        role: 'Regional Credit Head',
        name: 'Deepak Sharma',
        status: 'pending',
        comments: undefined,
        timestamp: undefined,
      },
      {
        id: 'STEP004',
        role: 'Sanctioning Authority',
        name: 'Vikram Mehta (VP - Credit)',
        status: 'pending',
        comments: undefined,
        timestamp: undefined,
      },
    ],
    urgencyLevel: 'Priority',
    targetDate: '2024-01-20',
    slaStatus: 'Within SLA',
  },
  recommendation: {
    decision: 'Conditional Approve',
    rationale:
      'The applicant demonstrates strong business fundamentals with 12 years of operational history, reputed OEM customer base, and clean credit history. Financial ratios are within acceptable limits with DSCR of 2.1x providing adequate cushion. The collateral coverage is comfortable at 52.5% LTV. While the auto sector cyclicality and receivables concentration pose moderate risks, the diversified customer base and promoter experience provide adequate mitigants.',
    conditions: [
      'Sanction amount reduced to ₹6.30 Cr (10% haircut) to maintain conservative LTV',
      'Physical verification of factory premises to be completed before disbursement',
      'Updated valuation report not older than 3 months at time of disbursement',
      'Confirmation of order book from top 2 customers to be obtained',
      'Key machinery to be insured with bank clause within 15 days of disbursement',
      'Reference check with existing banker (HDFC Bank) to be satisfactory',
    ],
    mitigants: [
      'Promoter has provided personal guarantee for the facility',
      'Cross-collateral of residential property available if required',
      'ESCROW mechanism for receivables from top customers can be implemented',
      'Quarterly review of account conduct mandated',
    ],
    analystName: 'Priya Verma',
    analystDesignation: 'Senior Credit Analyst',
    recommendationDate: '2024-01-16',
  },
};
