import { LoanApplication, Policy, PolicySection, RiskAssessment } from '@/types/loan';

export const mockLoans: LoanApplication[] = [
  {
    id: 'LN-2024-001',
    customerName: 'Diamond Agencies Pvt Ltd',
    loanAmount: 5000000,
    loanType: 'Working Capital',
    assignedAnalyst: 'Rahul Sharma',
    status: 'Under Review',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-16'),
    teamName: 'Team Supermoney',
  },
  {
    id: 'LN-2024-002',
    customerName: 'Sunrise Enterprises',
    loanAmount: 2500000,
    loanType: 'Equipment Finance',
    assignedAnalyst: 'Priya Patel',
    status: 'Pre-Approved',
    createdAt: new Date('2024-01-14'),
    updatedAt: new Date('2024-01-15'),
    teamName: 'Team Supermoney',
  },
  {
    id: 'LN-2024-003',
    customerName: 'Metro Traders',
    loanAmount: 1000000,
    loanType: 'Overdraft',
    assignedAnalyst: 'Amit Kumar',
    status: 'Draft',
    createdAt: new Date('2024-01-13'),
    updatedAt: new Date('2024-01-13'),
    teamName: 'Team Supermoney',
  },
  {
    id: 'LN-2024-004',
    customerName: 'Greenfield Industries',
    loanAmount: 7500000,
    loanType: 'Business Expansion',
    assignedAnalyst: 'Rahul Sharma',
    status: 'Approved',
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-01-12'),
    teamName: 'Team Supermoney',
  },
  {
    id: 'LN-2024-005',
    customerName: 'Royal Textiles',
    loanAmount: 3000000,
    loanType: 'Term Loan',
    assignedAnalyst: 'Priya Patel',
    status: 'Processing',
    createdAt: new Date('2024-01-08'),
    updatedAt: new Date('2024-01-11'),
    teamName: 'Team Supermoney',
  },
];

export const bureauCompanyPolicies: Policy[] = [
  {
    id: 'age-norms',
    name: 'Age Norms – Primary (23–65 years)',
    description: 'Primary applicant must be between 23 and 65 years old',
    threshold: '23 ≤ Age ≤ 65',
    actualValue: 42,
    status: 'pass',
    dataSource: 'Personal Bureau',
  },
  {
    id: 'willful-defaulter',
    name: 'Not a Willful Defaulter',
    description: 'Applicant should not be a willful defaulter',
    threshold: 'Count = 0',
    actualValue: 0,
    status: 'pass',
    dataSource: 'Combined Bureau',
  },
  {
    id: 'wo-suit',
    name: 'Not WO / Suit Filed / DBT / SUB (Last 12 Months)',
    description: 'No write-offs or suits filed in recent past',
    threshold: 'Count = 0',
    actualValue: 0,
    status: 'pass',
    dataSource: 'Combined Bureau',
  },
  {
    id: 'delay-60',
    name: 'Not in 60+ Delay (Last 12 Months)',
    description: 'No major delinquencies in last 12 months',
    threshold: 'Count = 0',
    actualValue: 0,
    status: 'pass',
    dataSource: 'Combined Bureau',
  },
  {
    id: 'delay-30',
    name: 'Not in 30+ Delay (Last 6 Months)',
    description: 'No 30+ DPD accounts in last 6 months',
    threshold: 'Count = 0',
    actualValue: 1,
    status: 'fail',
    dataSource: 'Combined Bureau',
  },
  {
    id: 'no-npa',
    name: 'No NPA',
    description: 'No non-performing assets in credit profile',
    threshold: 'Count = 0',
    actualValue: 0,
    status: 'pass',
    dataSource: 'Commercial Bureau',
  },
  {
    id: 'no-writeoff',
    name: 'No Write-offs / Restructure in Last 10 Years',
    description: 'No write-offs or restructures in last 10 years',
    threshold: 'Count = 0',
    actualValue: 0,
    status: 'pass',
    dataSource: 'Combined Bureau',
  },
];

export const bureauOtherPolicies: Policy[] = [
  {
    id: 'individual-score',
    name: 'Individual Score > 680',
    description: 'Personal credit score must exceed 680',
    threshold: 'Score > 680',
    actualValue: null,
    status: 'not-available',
    dataSource: 'Personal Bureau',
  },
  {
    id: 'cmr-score',
    name: 'Commercial Score CMR ≤ 6',
    description: 'Commercial credit risk must be CMR-6 or better',
    threshold: 'CMR ≤ 6',
    actualValue: 3,
    status: 'pass',
    dataSource: 'Commercial Bureau',
  },
  {
    id: 'cc-overdue',
    name: 'Credit Card Overdue ≤ ₹10,000',
    description: 'Total credit card overdue should not exceed ₹10,000',
    threshold: '≤ ₹10,000',
    actualValue: '₹5,200',
    status: 'pass',
    dataSource: 'Personal Bureau',
  },
  {
    id: 'enquiries-3m',
    name: 'Total Enquiries ≤ 7 (Last 3 Months)',
    description: 'Recent credit seeking should be limited',
    threshold: '≤ 7',
    actualValue: 4,
    status: 'pass',
    dataSource: 'Commercial Bureau',
  },
  {
    id: 'unsecured-ratio',
    name: 'Unsecured Funding / Turnover < 25%',
    description: 'Control excessive unsecured leverage',
    threshold: '< 25%',
    actualValue: '18.5%',
    status: 'pass',
    dataSource: 'Combined Bureau',
  },
  {
    id: 'thick-bureau',
    name: 'Thick Bureau (≥ 2 Years Vintage)',
    description: 'Sufficient bureau history depth required',
    threshold: '≥ 2 loans with 2+ years vintage',
    actualValue: 4,
    status: 'pass',
    dataSource: 'Combined Bureau',
  },
  {
    id: 'stability',
    name: 'Stability – 6 Months Stability',
    description: 'Single PIN code in last 6 months',
    threshold: '1 PIN code',
    actualValue: 1,
    status: 'pass',
    dataSource: 'Personal Bureau',
  },
  {
    id: 'outstanding-ratio',
    name: 'Outstanding / Sanctioned < 60%',
    description: 'Prevent over-leveraging',
    threshold: '< 60%',
    actualValue: '72%',
    status: 'fail',
    dataSource: 'Combined Bureau',
  },
];

export const bankingCompanyPolicies: Policy[] = [
  {
    id: 'inward-bounce',
    name: 'Inward Cheque Bounce ≤ 3%',
    description: 'Payment discipline based on inward cheque clearances',
    threshold: '≤ 3%',
    actualValue: '1.8%',
    status: 'pass',
    dataSource: 'Bank Statement',
  },
  {
    id: 'outward-bounce',
    name: 'Outward Cheque Bounce ≤ 5%',
    description: 'Repayment reliability and outward payment behaviour',
    threshold: '≤ 5%',
    actualValue: '3.2%',
    status: 'pass',
    dataSource: 'Bank Statement',
  },
  {
    id: 'emi-bounce',
    name: 'EMI Bounce ≤ 2%',
    description: 'Loan servicing discipline through EMI repayment',
    threshold: '≤ 2%',
    actualValue: '0.5%',
    status: 'pass',
    dataSource: 'Bank Statement + EMI',
  },
];

export const bankingOtherPolicies: Policy[] = [
  {
    id: 'cash-deposit',
    name: 'Cash Deposit % < 20%',
    description: 'Proportion of cash-based inflows',
    threshold: '< 20%',
    actualValue: '15.3%',
    status: 'pass',
    dataSource: 'Bank Transactions',
  },
  {
    id: 'cash-withdrawal',
    name: 'Cash Withdrawal % < 20%',
    description: 'Extent of cash-based outflows',
    threshold: '< 20%',
    actualValue: '22.1%',
    status: 'fail',
    dataSource: 'Bank Transactions',
  },
];

export const gstCompanyPolicies: Policy[] = [
  {
    id: 'turnover-drop',
    name: 'Turnover Drop ≤ 30%',
    description: 'Revenue stability comparing 3-month vs 6-month average',
    threshold: '≤ 30%',
    actualValue: '12%',
    status: 'pass',
    dataSource: 'GST Returns',
  },
  {
    id: 'gst-compliant',
    name: 'GST Compliant',
    description: 'Delayed filings should not exceed 20%',
    threshold: 'Delayed ≤ 20%',
    actualValue: '8%',
    status: 'pass',
    dataSource: 'GST Returns',
  },
  {
    id: 'gst-filed-2m',
    name: 'GST Filed (2 Months Before)',
    description: 'Recent GST compliance prior to bureau report',
    threshold: 'Filed',
    actualValue: 'Not Filed',
    status: 'fail',
    dataSource: 'GST Returns',
  },
  {
    id: 'debtor-concentration',
    name: 'Debtor Concentration – Top Supplier ≤ 50%',
    description: 'Dependency risk on single supplier',
    threshold: '≤ 50%',
    actualValue: '58%',
    status: 'fail',
    dataSource: 'GST Returns',
  },
  {
    id: 'vendor-concentration',
    name: 'Vendor Concentration – Top Customer ≤ 50%',
    description: 'Revenue dependency on single customer',
    threshold: '≤ 50%',
    actualValue: '35%',
    status: 'pass',
    dataSource: 'GST Returns',
  },
];

export const gstOtherPolicies: Policy[] = [
  {
    id: 'business-vintage',
    name: 'Business Vintage ≥ 2 Years',
    description: 'Operational stability of the business',
    threshold: '≥ 2 years',
    actualValue: '4 years',
    status: 'pass',
    dataSource: 'GST Returns',
  },
  {
    id: 'min-turnover',
    name: 'Minimum Turnover > ₹2 Crores',
    description: 'Business meets minimum scale requirement',
    threshold: '> ₹2 Cr',
    actualValue: '₹4.2 Cr',
    status: 'pass',
    dataSource: 'GST Returns',
  },
  {
    id: 'gst-6m',
    name: 'GST Filing Status (Last 6 Months)',
    description: 'Short-term GST compliance behaviour',
    threshold: '0 delays',
    actualValue: 0,
    status: 'pass',
    dataSource: 'GST Returns',
  },
];

export const crossDocPolicies: Policy[] = [
  {
    id: 'bto-ratio',
    name: 'Bank Turnover Ratio (BTO) – 70% to 140%',
    description: 'Alignment between Bank Statement and GST turnover',
    threshold: '70% - 140%',
    actualValue: '95%',
    status: 'pass',
    dataSource: 'Bank + GST',
  },
  {
    id: 'business-loans',
    name: 'Business Loans Value < 20% of Turnover',
    description: 'Leverage risk compared to annual turnover',
    threshold: '< 20%',
    actualValue: '14%',
    status: 'pass',
    dataSource: 'Bureau + GST',
  },
  {
    id: 'avg-balance',
    name: 'Average Bank Balance > 3% of Turnover',
    description: 'Liquidity adequacy assessment',
    threshold: '> 3%',
    actualValue: '5.2%',
    status: 'pass',
    dataSource: 'Bank + GST',
  },
];

export const mockRiskAssessment: RiskAssessment = {
  criteriaPassed: 46,
  criteriaFailed: 9,
  overallRiskScore: 84,
  riskCategory: 'Low Risk',
  keyStrengths: [
    'Commercial CIBIL Score is strong with CMR-3 rating, indicating low probability of default',
    'No willful defaults or suits filed in the last 12 months',
    'Unsecured funding to turnover ratio remains within acceptable limits',
    'Business demonstrates strong operational stability with 4+ years vintage',
  ],
  keyConcerns: [
    'Personal CIBIL score data is unavailable, critical for individual credit risk evaluation',
    'Outstanding to sanctioned amount ratio exceeds 60% limit, indicating potential over-leverage',
    'High debtor concentration with top supplier at 58%, increasing dependency risk',
    'GST returns for recent period not filed, raising compliance concerns',
  ],
  recommendations: [
    'Obtain and review Personal CIBIL score to complete individual credit risk assessment',
    'Take corrective steps to reduce outstanding to sanctioned ratio below 60%',
    'Diversify supplier base to reduce debtor concentration below 50%',
    'Ensure timely GST return filings to maintain compliance',
  ],
};

export const analysts = ['Rahul Sharma', 'Priya Patel', 'Amit Kumar', 'Sneha Gupta'];
