import { PersonalDiscussionData } from '@/types/personalDiscussion';

export const mockPersonalDiscussionData: PersonalDiscussionData = {
  applicantDetails: {
    name: 'Rajesh Sharma',
    designation: 'Managing Director',
    phone: '+91 98765 43210',
    email: 'rajesh.sharma@technocraft.in',
    interviewDate: '2024-01-15',
    interviewMode: 'In-Person',
    interviewedBy: 'Priya Verma',
  },
  businessDetails: {
    businessName: 'Technocraft Industries Pvt. Ltd.',
    constitution: 'Private Limited Company',
    yearsInBusiness: 12,
    industry: 'Manufacturing - Auto Components',
    productServices: 'Precision auto components, CNC machined parts, die casting components',
    numberOfEmployees: 85,
    businessPremises: 'Owned',
    keyCustomers: ['Maruti Suzuki India Ltd.', 'Tata Motors', 'Mahindra & Mahindra', 'Hero MotoCorp'],
    keySuppliers: ['Hindalco Industries', 'Tata Steel', 'JSW Steel', 'Vedanta Aluminium'],
  },
  financialDiscussion: {
    currentTurnover: 125000000,
    projectedGrowth: 18,
    profitMargin: 12.5,
    existingLoans: 35000000,
    proposedEMI: 850000,
    otherIncome: 'Rental income from commercial property - ₹1.5 Lakh/month',
    bankingRelationship: 'Primary banking with HDFC Bank since 2015, secondary with ICICI Bank',
    creditCardUsage: 'Regular',
  },
  interviewNotes: [
    {
      id: 'IN001',
      category: 'Business',
      question: 'What is your current capacity utilization and expansion plans?',
      response: 'Currently operating at 75% capacity. Planning to add new CNC machines to increase production by 40% to meet growing demand from OEMs.',
      observation: 'Applicant demonstrated clear understanding of business operations and growth strategy. Has purchase orders worth ₹8 Cr for next quarter.',
      riskIndicator: 'positive',
      timestamp: '2024-01-15T10:30:00',
    },
    {
      id: 'IN002',
      category: 'Financial',
      question: 'How do you plan to service the proposed EMI along with existing obligations?',
      response: 'Current monthly surplus after all expenses is ₹18-20 Lakhs. With projected growth, this should increase to ₹25 Lakhs. Proposed EMI of ₹8.5 Lakhs is well within capacity.',
      observation: 'Financial projections appear realistic based on order book. However, dependent on timely payment from OEM customers.',
      riskIndicator: 'positive',
      timestamp: '2024-01-15T10:45:00',
    },
    {
      id: 'IN003',
      category: 'Character',
      question: 'Have you faced any payment delays or defaults in the past?',
      response: 'Never defaulted on any payment. Had minor delays (5-10 days) during COVID period in 2020 due to receivables blockage, but cleared all dues promptly.',
      observation: 'Bureau report confirms clean track record. COVID delays were industry-wide and applicant managed well.',
      riskIndicator: 'positive',
      timestamp: '2024-01-15T11:00:00',
    },
    {
      id: 'IN004',
      category: 'Collateral',
      question: 'What collateral are you offering for this loan?',
      response: 'Offering factory premises at Plot 45, Industrial Area Phase II. Also have residential property in Sector 22 as additional security if required.',
      observation: 'Primary collateral has clear title. Factory valuation done 6 months ago at ₹12 Cr. LTV ratio comfortable at 58%.',
      riskIndicator: 'positive',
      timestamp: '2024-01-15T11:15:00',
    },
    {
      id: 'IN005',
      category: 'Capacity',
      question: 'What if there is a slowdown in the auto sector?',
      response: 'We have diversified to 4 major OEMs and also supply to the aftermarket. Exploring aerospace components as a new vertical.',
      observation: 'Diversification strategy is good but aerospace entry may take 2-3 years. Current dependence on auto sector remains a concern.',
      riskIndicator: 'neutral',
      timestamp: '2024-01-15T11:30:00',
    },
    {
      id: 'IN006',
      category: 'Business',
      question: 'How do you manage working capital cycles?',
      response: 'Typically maintain 30-45 days of raw material inventory. Payment terms are 60-90 days from OEMs. We have CC limit of ₹2 Cr which helps bridge the gap.',
      observation: 'Working capital cycle of 90-120 days is typical for the industry. Current CC limit utilization at 70% indicates moderate stress.',
      riskIndicator: 'neutral',
      timestamp: '2024-01-15T11:45:00',
    },
    {
      id: 'IN007',
      category: 'Financial',
      question: 'Any contingent liabilities or guarantees given?',
      response: 'I have given personal guarantee for the existing term loan of ₹3.5 Cr. No other contingent liabilities.',
      observation: 'Personal guarantee indicates commitment. No adverse information on contingent liabilities.',
      riskIndicator: 'positive',
      timestamp: '2024-01-15T12:00:00',
    },
    {
      id: 'IN008',
      category: 'General',
      question: 'What is your succession plan for the business?',
      response: 'My son, age 28, has recently joined after completing MBA from IIM Bangalore. He handles operations and planning to take over in 5-7 years.',
      observation: 'Good succession planning in place. Son has relevant education and is actively involved in operations.',
      riskIndicator: 'positive',
      timestamp: '2024-01-15T12:15:00',
    },
  ],
  characterAssessment: {
    firstImpression: 'Excellent',
    communicationSkills: 'Good',
    transparency: 'High',
    businessKnowledge: 'Expert',
    attitudeToRepayment: 'Committed',
    overallImpression: 'Mr. Sharma presents himself as an experienced industrialist with deep understanding of his business. He was forthcoming with information and did not hesitate to discuss challenges. His conservative approach to business expansion and focus on quality customers indicates prudent management.',
  },
  summary: {
    strengths: [
      'Strong business presence with 12 years of operation',
      'Reputed OEM customer base with diversified revenue',
      'Clean credit history with no defaults',
      'Adequate collateral coverage with owned factory premises',
      'Experienced management with succession plan in place',
      'Healthy profit margins above industry average',
    ],
    concerns: [
      'High dependence on auto sector which is cyclical',
      'Working capital cycle indicates moderate stress',
      'Proposed expansion dependent on single new machinery supplier',
      'Receivables concentration with top 2 customers at 45%',
    ],
    recommendations: [
      'Proceed with loan approval with standard terms',
      'Mandate quarterly review of receivables aging',
      'Insurance requirement for key machinery to be funded',
      'Cross-collateral of residential property recommended but not mandatory',
      'Sanction 10% lower amount to maintain conservative LTV',
    ],
    overallAssessment: 'Favorable',
    confidenceScore: 82,
    verificationRequired: [
      'Physical verification of factory premises',
      'Confirmation of order book from top 2 customers',
      'Updated valuation of collateral property',
      'Reference check with existing banker (HDFC Bank)',
    ],
  },
};
